Expose HIGHESTMODSEQ value in EXPUNGE response
jonhoo/rust-imap pull request #234
Opened 2022-07-14 10:07 UTC by bitfehler

If the `QRESYNC` extension (RFC 7162) is being used, `EXPUNGE` responses
will return the new highest mod sequence for the mailbox after the
expunge operation. Access to this value is quite valuable for caching
clients.

2022-07-14 10:08 UTC, bitfehler commented
This one is a bit more involved. I tried to do it in such a way that the API stays essentially the same except for one added field. But I am open for suggestions if you think this would be better handled differently.

2022-07-14 11:57 UTC, jonhoo requested changes
This looks great! Would you mind adding a test or two to make sure this actually works too?

2022-07-14 11:57 UTC, jonhoo commented on src/types/deleted.rs
> +pub struct Deleted {
Let's mark this as `#[non_exhaustive]` in case we realize there are other expunge details we want to add in the future.

2022-07-16 14:22 UTC, jonhoo approved these changes
No, that's perfect,thanks!

2022-07-16 14:22 UTC, jonhoo commented
I do wonder if your CI mail server (Greenmail) supports QRESYNC.. If so, we should be able to write an integration test too, not just a parsing test. But no need for that in this PR.

2022-07-16 14:36 UTC, merged