Refactor tag assertion to FatalError check & Fix unexpected increase of tag (fork)
jonhoo/rust-imap pull request #284
Opened 2024-03-24 08:34 UTC by soywod

This is just a fork of https://github.com/jonhoo/rust-imap/pull/231 so it can be finished and merged.

2024-03-24 08:42 UTC, soywod commented
One [test fails](https://github.com/jonhoo/rust-imap/actions/runs/8408073328/job/23023789923?pr=284) but it is not related to this PR.

2024-03-30 16:36 UTC, jonhoo requested changes
Thanks for picking this up!

2024-03-30 16:36 UTC, jonhoo commented on src/error.rs
> +    }
You can remove both of these impls — their default impl is fine.

2024-03-30 16:36 UTC, jonhoo commented on src/error.rs
> +    pub(crate) actual: u32,
Let's make this a `Result<u32, Vec<u8>>` instead so we can directly present the unparseable tag if present.

2024-03-30 16:36 UTC, jonhoo commented on src/error.rs
> +#[derive(Debug)]
```suggestion
#[derive(Debug, Clone, PartialEq, Eq)]
```

2024-03-30 16:36 UTC, jonhoo commented on src/error.rs
> +    /// Tag mismatch between client and server. New session must be created.
```suggestion
    /// The server responded with a different command tag than the one we just sent.
    ///
    /// A new session must generally be established to recover from this.
```

2024-03-30 16:36 UTC, jonhoo commented on src/error.rs
> +/// Tag was corrupted during session.
```suggestion
/// The server responded with a different command tag than last one we sent.
```

2024-03-30 16:36 UTC, jonhoo commented on src/client.rs
> +impl<T: Read + Write> Client<T> {
Let's move this to be on `Connection` instead.

2024-03-30 16:36 UTC, jonhoo commented on src/client.rs
> +    /// Manually increment the current tag.
Could you expand the docs a bit more here to indicate why someone may want to use this method?

2024-03-30 19:41 UTC, soywod commented
Ready for a second review.

2024-03-31 07:33 UTC, jonhoo approved these changes
Thanks! I want to tweak the docs a little more, but can do that locally. Let's get this merged :tada:

2024-03-31 07:34 UTC, merged

2024-03-31 07:49 UTC, soywod commented
> Let's get this merged

Awesome, thank you! Do you think it could be possible to release a new
alpha version? I need this fix to release a new version of mine.

2024-03-31 07:54 UTC, jonhoo commented
Yep, it's coming shortly! I'm preparing it over here: https://github.com/jonhoo/rust-imap/pull/285

The specific doc changes I made are these: https://github.com/jonhoo/rust-imap/pull/285/commits/ed433ec5745a3dfb1aaecc22bbbe5d834d5c33dd

2024-03-31 08:39 UTC, jonhoo commented
Published as 3.0.0-alpha.13 :tada: